### ISSUE TITLE
Add sobelow (security scanner) to CI

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/auth#11]

**Comment by jinjagit** [comment]
Initial explorations indicate this may not be great in CI, due to large number of false positives being possible (Sobelow tends to over-report). Certainly, could be a useful tool, but maybe just not for GitHub CI checks. I will experiment.

**Comment by oliverbarnes** [comment]
🤔 it looks in `config/prod.exs`, which I'm guessing it defaults to. Both `auth` and `api` apps are actually using `config/releases.exs`, thought the `MIX_ENV` is `prod`. I wonder if there's a way to make Sobelow look at the latter instead?

**Comment by jinjagit** [comment]
> it looks in `config/prod.exs`, which I'm guessing it defaults to. Both `auth` and `api` apps are actually using `config/releases.exs`, thought the `MIX_ENV` is `prod`. I wonder if there's a way to make Sobelow look at the latter instead?

I'll look into this.

**Comment by jinjagit** [comment]
I haven't found any way of specifying where it looks and for what. The [docs](https://hexdocs.pm/sobelow/readme.html) seem to only include options for ignore or skip, (where it should not look, or what it should not check for), not include, target, or any other additional scanning instructions.

**Comment by oliverbarnes** [comment]
Closing this for now, I think we're better off looking for better suited tools
