### ISSUE TITLE
Add smoke test at the end of CI

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/auth#26]

**Comment by jinjagit** [comment]
already exists: #23

**Comment by jinjagit** [comment]
- [ ]  Create k6 smoke test

- [ ]  Add test data teardown function(s) to release.ex

- [ ] Add smoke test action to `on_push.yml` CI, after deploy action

**Comment by oliverbarnes** [comment]
we can reuse both the smoke tests and api release teardown script, so all that needs to be added is the smoke test action to `on_push.yml` here

**Comment by jinjagit** [comment]
We don't want to test the create org / delete org functions?

**Comment by oliverbarnes** [comment]
> We don't want to test the create org / delete org functions? 

No, these aren't accessible via API requests, they're internal to the service - orgs are created manually via kubectl, currently. Eventually we might have self-signup via web interface (#10) 

> We just want to test that the api still works after an auth deploy, since the auth service must be working for the api to be working, right?

Exactly 👍 hence the same smoke tests

**Comment by jinjagit** [comment]
Gotcha. _Should_ be relatively easy then (famous last words, I know)
