### ISSUE TITLE
Bump ssri to safe versions

### ISSUE THREAD

**Issue by davefrey** [liquidvotingio/auth#87]
This came on my github notifications; I don't see it in the repo Security tab but I confirmed that we still have two vulnerable versions on master. https://github.com/advisories/GHSA-vx3p-948g-6vhq

We should bump our `ssri` to 6.0.2 and 8.0.1. (it looks like we "resolved" to 6.0.2 but there is a 6.0.1 reference; idk how npm works).

Found with:
```
➜  auth git:(master) ag ssri
assets/package-lock.json
1698:        "ssri": "^6.0.1",
7264:    "ssri": {
7266:      "resolved": "https://registry.npmjs.org/ssri/-/ssri-6.0.2.tgz",
7578:            "ssri": "^7.0.0",
7678:        "ssri": {
7680:          "resolved": "https://registry.npmjs.org/ssri/-/ssri-7.1.0.tgz",
```

**Comment by oliverbarnes** [comment]
Thanks for opening this. Seems to be low risk given it only happens on browser rendered stuff (https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity), and `auth` is an internal api. Might be resolved in future version bumps?

**Comment by davefrey** [comment]
You dug deeper than I did, thanks, it seems safe to leave it.

I guess it would bump when we update phoenix?

I'll close though.
